/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */


__attribute__((visibility("hidden")))
@interface HNDDefaults {
}
+(id)sharedDefaults;
+(void)initialize;
-(void)setPreference:(id)preference forKey:(id)key;
-(id)preferenceForKey:(id)key;
@end

