/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"


__attribute__((visibility("hidden")))
@interface HNDInnerCircleView {
}
-(void)drawRect:(CGRect)rect;
@end

