/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"

@protocol HNDWindowDelegateProtocol;

__attribute__((visibility("hidden")))
@interface HNDWindow {
	id<HNDWindowDelegateProtocol> _hitTestDelegate;
}
@property(assign, nonatomic) id<HNDWindowDelegateProtocol> hitTestDelegate;
-(BOOL)acceptsGlobalPoint:(CGPoint)point;
@end

