/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */


@interface XXUnknownSuperclass (HNDView)
-(id)_axSubviews;
-(void)_axPrintSubviews:(int)subviews string:(id)string;
@end

